/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */
import type { GetApiV1AuthSession200Data } from './getApiV1AuthSession200Data';

export type GetApiV1AuthSession200 = {
  is_login?: boolean;
  data?: GetApiV1AuthSession200Data;
};
