/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */

export type PostApiV1AuthSignUpBody = {
  name: string;
  email: string;
  password: string;
  password_confirmation: string;
};
