/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */
import type {
  GetApiV1AuthSession200,
  PostApiV1AuthSignInBody,
  PostApiV1AuthSignUp201,
  PostApiV1AuthSignUpBody,
} from '../schemas';
import { customInstance } from '../../api/customAxiosInstance';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const getPortfolioAuth = () => {
  /**
   * @summary ユーザーのログイン
   */
  const postApiV1AuthSignIn = (
    postApiV1AuthSignInBody: PostApiV1AuthSignInBody,
    options?: SecondParameter<typeof customInstance>,
  ) => {
    return customInstance<void>(
      {
        url: `/api/v1/auth/sign_in`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postApiV1AuthSignInBody,
      },
      options,
    );
  };
  /**
   * @summary ユーザー登録
   */
  const postApiV1AuthSignUp = (
    postApiV1AuthSignUpBody: PostApiV1AuthSignUpBody,
    options?: SecondParameter<typeof customInstance>,
  ) => {
    return customInstance<PostApiV1AuthSignUp201>(
      {
        url: `/api/v1/auth/sign_up`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: postApiV1AuthSignUpBody,
      },
      options,
    );
  };
  /**
   * @summary 現在のセッション情報を取得
   */
  const getApiV1AuthSession = (
    options?: SecondParameter<typeof customInstance>,
  ) => {
    return customInstance<GetApiV1AuthSession200>(
      { url: `/api/v1/auth/session`, method: 'GET' },
      options,
    );
  };
  return { postApiV1AuthSignIn, postApiV1AuthSignUp, getApiV1AuthSession };
};
export type PostApiV1AuthSignInResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPortfolioAuth>['postApiV1AuthSignIn']>
  >
>;
export type PostApiV1AuthSignUpResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPortfolioAuth>['postApiV1AuthSignUp']>
  >
>;
export type GetApiV1AuthSessionResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getPortfolioAuth>['getApiV1AuthSession']>
  >
>;
